# Generated by Django 3.1.6 on 2024-01-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='description',
            field=models.TextField(default='JE suis un membre anonyme du forum'),
        ),
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.TextField(default='JE suis un membre anonyme du forum'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.postmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.users')),
            ],
        ),
    ]
