# Generated by Django 3.1.6 on 2024-02-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240118_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
